version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/packages/frontend
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/packages/backend
    command: ["npm", "start"]
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
